export const menuItems = [
  { label: 'About', accent: '#C9963A', gradient: 'linear-gradient(145deg, #102438 0%, #09111D 58%, #C9963A 140%)' },
  { label: 'Services', accent: '#D7B66B', gradient: 'linear-gradient(145deg, #172A3E 0%, #0A1520 55%, #D7B66B 145%)' },
  { label: 'Portfolio', accent: '#86A7C5', gradient: 'linear-gradient(145deg, #10283B 0%, #09111D 60%, #86A7C5 145%)' },
  { label: 'Start', accent: '#B98B3D', gradient: 'linear-gradient(145deg, #1D2632 0%, #0A1520 56%, #B98B3D 145%)' },
  { label: 'Insights', accent: '#E8BF6A', gradient: 'linear-gradient(145deg, #0E1D2D 0%, #080F18 58%, #E8BF6A 140%)' },
  { label: 'FAQ', accent: '#C9963A', gradient: 'linear-gradient(145deg, #102438 0%, #09111D 58%, #C9963A 140%)' },
  { label: 'Careers', accent: '#D7B66B', gradient: 'linear-gradient(145deg, #172A3E 0%, #0A1520 55%, #D7B66B 145%)' },
  { label: 'Referral', accent: '#86A7C5', gradient: 'linear-gradient(145deg, #10283B 0%, #09111D 60%, #86A7C5 145%)' },
  { label: 'Contact', accent: '#B98B3D', gradient: 'linear-gradient(145deg, #1D2632 0%, #0A1520 56%, #B98B3D 145%)' },
]

export const serviceLines = [
  'Business strategy and market positioning',
  'Investor-grade business plans and financial models',
  'Brand identity systems for launch-ready companies',
  'Websites, booking flows, payments, email and analytics',
  'Operational setup for companies in Nigeria and the UK',
  'Founder visa business planning and endorsement preparation',
]

export const pageData = {
  services: {
    eyebrow: 'Services',
    title: 'Choose the growth engine your business needs now.',
    intro: 'STACKZIRA is built for founders who need more than advice. We package strategy, brand, technology and operations into focused delivery tracks with clear outputs.',
    cta: 'Book a service call',
    ctaHref: '/contact',
    accent: '#C9963A',
    heroStat: '06',
    heroStatLabel: 'delivery tracks',
    sections: [
      { title: 'Strategy and planning', body: 'Market research, positioning, pricing, revenue models and execution roadmaps shaped into decisions you can act on immediately.' },
      { title: 'Brand and digital launch', body: 'Identity, website, domain, email, Google Business profile, social setup, payments and analytics delivered as a launch-ready platform.' },
      { title: 'Operations setup', body: 'Company registration guidance, banking, accounting tools, legal templates, payment infrastructure and admin foundations.' },
      { title: 'Founder visa support', body: 'Idea refinement, endorsement-grade business plans, financials, interview preparation and post-approval operating setup.' },
    ],
    proof: ['21-day launch sprint', 'Brand system included', 'Website up to 8 pages', 'No vague reports'],
  },
  about: {
    eyebrow: 'About STACKZIRA',
    title: 'An execution company for founders ready to launch.',
    intro: 'STACKZIRA gives founders the strategy, brand, digital presence and structure they need before growth tools can perform.',
    cta: 'Talk to the team',
    ctaHref: '/contact',
    accent: '#D7B66B',
    heroStat: 'LON',
    heroStatLabel: 'Lagos to London',
    sections: [
      { title: 'Why we exist', body: 'Strong founders often lose momentum because the execution foundation is missing: plan, brand, website, operations and funding narrative.' },
      { title: 'How we work', body: 'We keep delivery visible, structured and honest. You see progress, give feedback at the right moments and leave with usable assets.' },
      { title: 'The operating layer', body: 'STACKZIRA covers the practical business journey: setup, launch, operations, growth and everyday management.' },
      { title: 'Who we serve', body: 'Nigerian and diaspora entrepreneurs building companies that need to look credible, run properly and move fast.' },
    ],
    proof: ['Lagos and London context', 'Delivery-first consultancy', 'Built for African founders', 'Launch-ready execution'],
  },
  process: {
    eyebrow: 'How It Works',
    title: 'Twenty-one days. Clear rhythm. No surprises.',
    intro: 'The STACKZIRA delivery model turns an uncertain launch into a sequence of visible milestones: discovery, strategy, brand, build, test and handover.',
    cta: 'Start the countdown',
    ctaHref: '/contact',
    accent: '#86A7C5',
    heroStat: '21',
    heroStatLabel: 'days to launch',
    sections: [
      { title: 'Days 1-2: Discovery', body: 'We map the business, scope the work, confirm outputs and assign a project lead so everyone knows what is happening.' },
      { title: 'Days 3-9: Strategy and brand', body: 'We shape positioning, visual identity, content direction and the practical roadmap for the build.' },
      { title: 'Days 10-16: Build', body: 'The website, pages, integrations, profiles and operating assets are assembled in a live staging environment.' },
      { title: 'Days 17-21: Launch', body: 'We test, refine, connect domains, configure accounts and walk you through everything before handover.' },
    ],
    proof: ['Daily milestones', 'Staging preview', 'Testing included', 'Handover call'],
  },
  visa: {
    eyebrow: 'Founder Visa',
    title: 'Build the business case for the UK Innovator Founder route.',
    intro: 'We help entrepreneurs sharpen innovative, viable and scalable ideas into endorsement-ready business plans and operating foundations.',
    cta: 'Book eligibility call',
    ctaHref: '/contact',
    accent: '#B98B3D',
    heroStat: '3',
    heroStatLabel: 'core criteria',
    sections: [
      { title: 'Innovative', body: 'We clarify what is meaningfully different about the business, where the market gap sits and why the UK context matters.' },
      { title: 'Viable', body: 'We build the commercial model, financial projections, operations plan and risk narrative needed for serious assessment.' },
      { title: 'Scalable', body: 'We show how the company can grow: revenue, jobs, market reach, partnerships and long-term defensibility.' },
      { title: 'Prepared', body: 'We support endorsement packs, mock interviews, document organisation and post-approval launch planning.' },
    ],
    proof: ['Business plan writing', 'Financial projections', 'Endorsement preparation', 'Post-approval setup'],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Bring the business. We will map the next move.',
    intro: 'Start with a free discovery call. We will listen, diagnose the gap and recommend the service track that makes sense for where you are.',
    cta: 'Email STACKZIRA',
    ctaHref: 'mailto:hello@stackzira.com',
    accent: '#E8BF6A',
    heroStat: '30',
    heroStatLabel: 'minute call',
    sections: [
      { title: 'Email', body: 'hello@stackzira.com' },
      { title: 'WhatsApp', body: '+234 000 000 0000' },
      { title: 'Locations', body: 'Lagos, Nigeria and London, United Kingdom.' },
      { title: 'Response', body: 'Every enquiry receives a human reply within one business day.' },
    ],
    proof: ['No pressure', 'Clear recommendation', 'One business day reply', 'Free discovery call'],
  },
} as const
